services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./fastapi-backend
      dockerfile: ./backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi-backend/.env
    volumes:
      - ./fastapi-backend/app:/app/app
    restart: always